trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- script: echo "Pipeline funcionando"
  displayName: 'Teste da pipeline'

- script: docker --version
  displayName: 'Verificar Docker'

- script: docker-compose version
  displayName: 'Verificar Docker Compose'
