trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  resourceGroup: 'EasyPark-RG'
  vmName: 'easypark-vm'
  location: 'eastus'

steps:
- checkout: self

- task: AzureCLI@2
  displayName: 'Criar VM no Azure'
  inputs:
    azureSubscription: 'Sua-Conexao-Com-O-Azure'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az vm create \
        --resource-group $(resourceGroup) \
        --name $(vmName) \
        --image Ubuntu2204 \
        --admin-username azureuser \
        --generate-ssh-keys \
        --public-ip-sku Standard \
        --location $(location)
      
      az vm open-port \
        --port 80 \
        --resource-group $(resourceGroup) \
        --name $(vmName) \
        --priority 1001

- task: AzureCLI@2
  displayName: 'Coletar IP da VM'
  inputs:
    azureSubscription: 'Sua-Conexao-Com-O-Azure'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      vmIp=$(az vm list-ip-addresses --resource-group $(resourceGroup) --name $(vmName) --query "[0].virtualMachine.network.publicIpAddresses[0].ipAddress" -o tsv)
      
      mkdir artifact
      echo "EasyPark deploy em VM realizado" > artifact/deploy.txt
      echo "Seu app estará disponível no IP: http://$vmIp" >> artifact/deploy.txt

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'artifact'
    ArtifactName: 'easypark-artifact'
  displayName: 'Publicar Artifact'
